# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            J.Reed's Website
subtitle:         Personal profile and blog
description:      This is the personal profile and blog for Jeremy Reed.
keywords:         Jeremy Reed Developer Engineer Software Websites Blog Resume Portfolio
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /blog/:categories/:title
cover:            /assets/mountain-cover.jpg
disqus_shortname: ""

# Post defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
      author: jreed

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]